server:
  port: 8765
spring:
  application:
    name: @artifactId@ # 这个名字是用来服务之间调用时区分的
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #注册中心地址
feign:
  hystrix:
    enabled: true #开启feign的断路器功能