spring:
  application:
    name: @artifactId@
  cloud:
    config:
      label: master # 配置仓库的分支
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/ # 仓库地址
          search-paths: respo # 仓库路径
          username: # git 登录名，公开仓库可以不用写
          password: # git 登录密码
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #注册中心地址
