server:
  port: 8769
spring:
  application:
    name: @artifactId@ # 这个名字是用来服务之间调用时区分的
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #注册中心地址
debug: true
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign