spring:
  application:
    name: @artifactId@
  profiles:
    active: peer2
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer2:8761/eureka/
server:
  port: 8769
