server:
  port: 8762
spring:
  application:
    name: @artifactId@ # 这个名字是用来服务之间调用时区分的
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/, http://peer2:8769/eureka/ #注册中心地址
